spring:
  profiles:
    #    active: log, local, app
    active: log, prod, app
logging:
  level:
    root: debug
    sql: trace
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"